server:
  port: 8000

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
tequila:
  apiKey: ${SPRING_TEQUILA_API_KEY}
  baseUrl: https://tequila-api.kiwi.com/v2
dbBahn:
  baseUrl: https://v6.db.transport.rest/
environment: ${SPRING_ENV}
version: 0.0.1