server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.bsrmtjhnrzxpvwoxqvop&password=dV38LWUgPCXSPSc5
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
tequila:
  apiKey: BhUIsil5ss0_-KflWEsay8guLOoxuVt7
  baseUrl: https://tequila-api.kiwi.com/v2
dbBahn:
  baseUrl: https://v6.db.transport.rest/
busApi:
  baseUrl: https://bus.api.wanderbyway.com
environment: local
version: 0.0.2