server:
  port: 8000
mongock:
  migration-scan-package:
    - com.herbert.travelapp.api.changelogs

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: wanderTravel
      auto-index-creation: true
tequila:
  apiKey: BhUIsil5ss0_-KflWEsay8guLOoxuVt7
  baseUrl: https://tequila-api.kiwi.com/v2
direkt-bahn:
  RouteUrl: https://api.direkt.bahn.guru
  SearchUrl: https://v5.db.juliustens.eu/locations
open-cage:
  api-key: 153c5117a83e4062988a2745c713dc52