server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.bsrmtjhnrzxpvwoxqvop&password=dV38LWUgPCXSPSc5
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
tequila:
  apiKey: BhUIsil5ss0_-KflWEsay8guLOoxuVt7
  baseUrl: https://tequila-api.kiwi.com/v2
open-cage:
  api-key: 153c5117a83e4062988a2745c713dc52
dbBahn:
  baseUrl: https://v6.db.transport.rest/