server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.bsrmtjhnrzxpvwoxqvop&password=dV38LWUgPCXSPSc5
    username: postgres
    password: dV38LWUgPCXSPSc5
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
tequila:
  apiKey: BhUIsil5ss0_-KflWEsay8guLOoxuVt7
  baseUrl: https://tequila-api.kiwi.com/v2
direkt-bahn:
  RouteUrl: https://api.direkt.bahn.guru
  SearchUrl: https://v5.db.juliustens.eu/locations
open-cage:
  api-key: 153c5117a83e4062988a2745c713dc52